In [1]:
import numpy as np
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go

In [2]:
data_daily = pd.read_csv('04 Case Information.csv')
data_daily.head(2)

,CaseCode,Age,AgeGroup,Sex,DateSpecimen,DateResultRelease,DateRepConf,DateDied,DateRecover,RemovalType,Admitted,RegionRes,ProvRes,CityMunRes,CityMuniPSGC,HealthStatus,Quarantined,DateOnset,Pregnanttab,ValidationStatus
0,C217616,1.0,0 to 4,MALE,2020-04-23,2020-04-26,2020-04-27,NaN,NaN,RECOVERED,NO,NCR,NaN,NaN,NaN,RECOVERED,NO,2020-04-23,NaN,"Removal Type is ""Recovered"", but no Recovered ..."
1,C749500,33.0,30 to 34,MALE,2020-04-28,2020-05-01,2020-05-02,NaN,2020-06-28,RECOVERED,NO,ROF,NaN,NaN,NaN,RECOVERED,NO,2020-04-28,NaN,NaN

In [3]:
data_daily.columns

Index(['CaseCode', 'Age', 'AgeGroup', 'Sex', 'DateSpecimen',
       'DateResultRelease', 'DateRepConf', 'DateDied', 'DateRecover',
       'RemovalType', 'Admitted', 'RegionRes', 'ProvRes', 'CityMunRes',
       'CityMuniPSGC', 'HealthStatus', 'Quarantined', 'DateOnset',
       'Pregnanttab', 'ValidationStatus'],
      dtype='object')

# Pasig City and Pasay City Data Only

In [4]:
# Pasay City Data
pasay_daily = data_daily.loc[(data_daily['CityMunRes']=='PASAY CITY'), :]
pasay_daily = pasay_daily.fillna('NO DATA')
pasay_daily['DateRepConf'] = pd.to_datetime(pasay_daily['DateRepConf'])
pasay_deaths = pasay_daily.loc[(pasay_daily['RemovalType']==
                               'DIED'), :]




# Pasig City Data
pasig_daily = data_daily.loc[(data_daily['CityMunRes']=='CITY OF PASIG'), :]
pasig_daily = pasig_daily.fillna('NO DATA')

pasig_deaths = pasig_daily.loc[(pasig_daily['RemovalType']==
                               'DIED'), :]




# Combined Data
both_daily = data_daily.loc[(data_daily['CityMunRes']=='PASAY CITY') | 
                            (data_daily['CityMunRes']=='CITY OF PASIG'), :]

# Pasay City Data

In [5]:
pasay_daily.head(2)

,CaseCode,Age,AgeGroup,Sex,DateSpecimen,DateResultRelease,DateRepConf,DateDied,DateRecover,RemovalType,Admitted,RegionRes,ProvRes,CityMunRes,CityMuniPSGC,HealthStatus,Quarantined,DateOnset,Pregnanttab,ValidationStatus
35330,C895185,46,45 to 49,MALE,2020-04-28,NO DATA,2020-05-03,NO DATA,2020-05-26,RECOVERED,NO,NCR,NCR,PASAY CITY,PH137605000,RECOVERED,YES,2020-04-25,NO DATA,"Case has Lab Result, but Result Date is blank"
35331,C735452,40,40 to 44,FEMALE,2020-06-15,2020-06-18,2020-06-21,NO DATA,2020-07-07,RECOVERED,NO,NCR,NCR,PASAY CITY,PH137605000,RECOVERED,YES,2020-06-09,NO,NO DATA

### Epidemic Curve

In [8]:
pasay_onset = pasay_daily['DateRepConf'].value_counts()
pasay_onset = pasay_onset.rename_axis('DateRepConf').reset_index(name='Frequency')
pasay_onset = pasay_onset.sort_values(by='DateRepConf')
pasay_onset.set_index('DateRepConf', inplace=True)

pasay_onset = pasay_onset.resample('D').bfill().reset_index()
#pasay_onset['Weekly Moving Average'] = pasay_onset.Frequency.rolling(7).mean()
pasay_onset

    DateRepConf  Frequency
0    2020-03-09          1
1    2020-03-10          1
2    2020-03-11          1
3    2020-03-12          1
4    2020-03-13          1
5    2020-03-14          1
6    2020-03-15          1
7    2020-03-16          3
8    2020-03-17          3
9    2020-03-18          3
10   2020-03-19          3
11   2020-03-20          3
12   2020-03-21          3
13   2020-03-22          3
14   2020-03-23          1
15   2020-03-24          2
16   2020-03-25          2
17   2020-03-26          1
18   2020-03-27          2
19   2020-03-28          6
20   2020-03-29          6
21   2020-03-30          3
22   2020-03-31         12
23   2020-04-01         12
24   2020-04-02          8
25   2020-04-03         16
26   2020-04-04          1
27   2020-04-05          2
28   2020-04-06          9
29   2020-04-07          1
..          ...        ...
153  2020-08-09        116
154  2020-08-10        180
155  2020-08-11         89
156  2020-08-12         76
157  2020-08-13        124
158  2020-08-14        189
159  2020-08-15         91
160  2020-08-16         94
161  2020-08-17        110
162  2020-08-18        186
163  2020-08-19         73
164  2020-08-20         82
165  2020-08-21         69
166  2020-08-22        126
167  2020-08-23         34
168  2020-08-24        160
169  2020-08-25        102
170  2020-08-26        260
171  2020-08-27         54
172  2020-08-28         94
173  2020-08-29         74
174  2020-08-30        147
175  2020-08-31        194
176  2020-09-01         94
177  2020-09-02         40
178  2020-09-03         13
179  2020-09-04        141
180  2020-09-05         73
181  2020-09-06         50
182  2020-09-07         22

[183 rows x 2 columns]

In [ ]:
pasay_curve_all = px.bar(pasay_onset,
                         x='DateRepConf',
                         y='Frequency',
                         template='plotly_dark',
                         title='Pasay City Daily Case Graph (Confirmed)')

pasay_curve_all.show()

### Cases by Age (Histogram)

In [ ]:
pasay_hist_age = px.histogram(pasay_daily,
                              x='Age', nbins=10,
                              template='plotly_dark',
                              title='COVID-19 Cases by Age (Pasay City)')
pasay_hist_age.show()

### Deaths by Age (Histogram)

In [ ]:
pasay_hist_death_age = px.histogram(pasay_deaths,
                              x='Age', nbins=10,
                              template='plotly_dark',
                              title='COVID-19 Deaths by Age (Pasay City)')

pasay_hist_death_age.update_traces(marker_color='red')
pasay_hist_death_age.show()

### Deaths and Recoveries by Age (Stacked Histogram)

In [ ]:
pasay_hist_removal_age = px.histogram(pasay_daily,
                              x='Age', nbins=10,
                              template='plotly_dark',
                              color='RemovalType',
                              marginal='violin',
                              title='COVID-19 Deaths and Recoveries by Age (Pasay City)')
pasay_hist_removal_age.show()

# Pasig City Data

In [ ]:
pasig_daily.head(2)